import Router from "express";
import { creatorTasks, deledTasks, getAllTasks, getTask, updateTask } from "../controllers/tasks.controllers.js";
import validatorJwt from "../middlewares/validatorToken.js";
const tasksRouter = Router();
tasksRouter.post("/tasks", validatorJwt, creatorTasks);
tasksRouter.get("/tasks", validatorJwt, getAllTasks);
tasksRouter.delete("/tasks/:id", validatorJwt, deledTasks);
tasksRouter.get("/tasks/:id", validatorJwt, getTask);
tasksRouter.put("/tasks/:id", validatorJwt, updateTask);
export default tasksRouter;
